/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;

import logica.LstUsuarios;
import logica.Mails;
import persistencia.Archivo;

/**
 *
 * @author mimiuwu
 */
public class FrmCambiarContrasenia extends javax.swing.JFrame {

    private LstUsuarios coleccion;
    private boolean puedeCambiar = false;

    /**
     * Creates new form FrmEliminarUsuario
     */
    public FrmCambiarContrasenia(Point p, LstUsuarios coleccion) {
        initComponents();
        this.setLocation(p);
        this.coleccion = coleccion;
        lblCoinciden.setVisible(false);
        lblDebil.setVisible(false);
        lblMedio.setVisible(false);
        lblNoCoinciden.setVisible(false);
        lblSegura.setVisible(false);
        lblOlvide.setVisible(false);
        lblNoExiste.setVisible(false);
        lblContraseniaIncorrecta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCoinciden = new javax.swing.JLabel();
        lblSegura = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        lblContraseniaIncorrecta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDebil = new javax.swing.JLabel();
        lblNoExiste = new javax.swing.JLabel();
        lblNoCoinciden = new javax.swing.JLabel();
        lblMedio = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lblOlvide = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fieldContraseniaNueva2 = new javax.swing.JPasswordField();
        fieldContraseniaNueva1 = new javax.swing.JPasswordField();
        fieldContraseniaAntigua = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("CAMBIAR CONTRASEÑA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setText("Contraseña antigua");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setText("Contraseña nueva");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lblCoinciden.setForeground(new java.awt.Color(0, 204, 0));
        lblCoinciden.setText("Coinciden");
        jPanel1.add(lblCoinciden, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        lblSegura.setForeground(new java.awt.Color(0, 204, 51));
        lblSegura.setText("Segura");
        jPanel1.add(lblSegura, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));
        jPanel1.add(fieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 250, -1));

        lblContraseniaIncorrecta.setForeground(new java.awt.Color(204, 0, 51));
        lblContraseniaIncorrecta.setText("Contraseña incorrecta.");
        jPanel1.add(lblContraseniaIncorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        lblDebil.setForeground(new java.awt.Color(204, 0, 0));
        lblDebil.setText("Débil");
        jPanel1.add(lblDebil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 40, -1));

        lblNoExiste.setText("Usuario no existe.");
        jPanel1.add(lblNoExiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        lblNoCoinciden.setForeground(new java.awt.Color(204, 0, 0));
        lblNoCoinciden.setText("No coinciden");
        jPanel1.add(lblNoCoinciden, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        lblMedio.setForeground(new java.awt.Color(255, 204, 0));
        lblMedio.setText("Medio");
        jPanel1.add(lblMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jButton3.setText("Olvidé mi contraseña");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        lblOlvide.setText("La contraseña se ha enviado a su correo.");
        jPanel1.add(lblOlvide, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel6.setText("Repetir contraseña nueva");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        fieldContraseniaNueva2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContraseniaNueva2ActionPerformed(evt);
            }
        });
        fieldContraseniaNueva2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldContraseniaNueva2KeyReleased(evt);
            }
        });
        jPanel1.add(fieldContraseniaNueva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 250, -1));

        fieldContraseniaNueva1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldContraseniaNueva1FocusLost(evt);
            }
        });
        fieldContraseniaNueva1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldContraseniaNueva1KeyReleased(evt);
            }
        });
        jPanel1.add(fieldContraseniaNueva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 250, -1));
        jPanel1.add(fieldContraseniaAntigua, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondito.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean verificarMail(String mail) {
        return coleccion.existePorMail(mail);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (verificarMail(fieldUsuario.getText())) {
            try {
                lblOlvide.setVisible(true);
                lblNoExiste.setVisible(false);
                Mails mails = new Mails();
                mails.enviarMail(fieldUsuario.getText(), "Contraseña", "Su contraseña es " + coleccion.devolver(fieldUsuario.getText()).getPass().getContrasenia());
            } catch (MessagingException ex) {
                Logger.getLogger(FrmCambiarContrasenia.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            lblNoExiste.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (String.valueOf(fieldContraseniaNueva1.getPassword()).equals(String.valueOf(fieldContraseniaNueva2.getPassword())) && puedeCambiar && coleccion.devolver(fieldUsuario.getText()).getPass().getContrasenia().equals(String.valueOf(fieldContraseniaAntigua.getPassword()))) {
            coleccion.devolver(fieldUsuario.getText()).getPass().cambiarContrasenia(String.valueOf(fieldContraseniaNueva1.getPassword()));
            coleccion.devolver(fieldUsuario.getText()).devolverCambiosPass().actualizarLista();
            Archivo.getInstancia().registrarUsuario(coleccion);

            FrmPrincipal principal = new FrmPrincipal(this.getLocation(), coleccion);
            principal.setVisible(true);
            this.dispose();
        } else {
            lblContraseniaIncorrecta.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldContraseniaNueva1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldContraseniaNueva1FocusLost

    }//GEN-LAST:event_fieldContraseniaNueva1FocusLost

    private boolean verificarContraseniaMayusculas(String contrasenia) {
        for (int i = 0; i < contrasenia.length(); i++) {
            if (Character.isUpperCase(contrasenia.charAt(i))) {
                return true;
            }
        }
        return false;
    }

    private boolean verificarContraseniaNumeros(String contrasenia) {
        for (int i = 0; i < contrasenia.length(); i++) {
            if (Character.isDigit(contrasenia.charAt(i))) {
                return true;
            }
        }
        return false;
    }

    private void fieldContraseniaNueva1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldContraseniaNueva1KeyReleased
        if (verificarContraseniaMayusculas(String.valueOf(fieldContraseniaNueva1.getPassword())) && verificarContraseniaNumeros(String.valueOf(fieldContraseniaNueva1.getPassword()))) {
            lblSegura.setVisible(true);
            lblDebil.setVisible(false);
            lblMedio.setVisible(false);
            puedeCambiar = true;
        } else if (verificarContraseniaMayusculas(String.valueOf(fieldContraseniaNueva1.getPassword())) && !verificarContraseniaNumeros(String.valueOf(fieldContraseniaNueva1.getPassword()))) {
            lblSegura.setVisible(false);
            lblDebil.setVisible(false);
            lblMedio.setVisible(true);
            puedeCambiar = true;
        } else if (!verificarContraseniaMayusculas(String.valueOf(fieldContraseniaNueva1.getPassword())) && verificarContraseniaNumeros(String.valueOf(fieldContraseniaNueva1.getPassword()))) {
            lblSegura.setVisible(false);
            lblDebil.setVisible(false);
            lblMedio.setVisible(true);
            puedeCambiar = true;
        } else {
            lblSegura.setVisible(false);
            lblDebil.setVisible(true);
            lblMedio.setVisible(false);
            puedeCambiar = false;
        }
    }//GEN-LAST:event_fieldContraseniaNueva1KeyReleased

    private void fieldContraseniaNueva2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContraseniaNueva2ActionPerformed

    }//GEN-LAST:event_fieldContraseniaNueva2ActionPerformed

    private void fieldContraseniaNueva2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldContraseniaNueva2KeyReleased
        if (String.valueOf(fieldContraseniaNueva1.getPassword()).equals(String.valueOf(fieldContraseniaNueva2.getPassword()))) {
            lblCoinciden.setVisible(true);
            lblNoCoinciden.setVisible(false);
        } else {
            lblCoinciden.setVisible(false);
            lblNoCoinciden.setVisible(true);
        }
    }//GEN-LAST:event_fieldContraseniaNueva2KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmSesion sesion = new FrmSesion(this.getLocation(), coleccion);
        sesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCambiarContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCambiarContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCambiarContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCambiarContrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCambiarContrasenia(new Point(0, 0), new LstUsuarios()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField fieldContraseniaAntigua;
    private javax.swing.JPasswordField fieldContraseniaNueva1;
    private javax.swing.JPasswordField fieldContraseniaNueva2;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCoinciden;
    private javax.swing.JLabel lblContraseniaIncorrecta;
    private javax.swing.JLabel lblDebil;
    private javax.swing.JLabel lblMedio;
    private javax.swing.JLabel lblNoCoinciden;
    private javax.swing.JLabel lblNoExiste;
    private javax.swing.JLabel lblOlvide;
    private javax.swing.JLabel lblSegura;
    // End of variables declaration//GEN-END:variables
}
